# Generated by Django 4.2.20 on 2025-04-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_is_encrypted_message_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='blockchain_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='integrity_verified',
            field=models.BooleanField(default=False),
        ),
    ]
