# Generated by Django 4.2.20 on 2025-04-05 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userkey',
            name='public_key_hash',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_message', models.UUIDField(blank=True, null=True)),
                ('reported_item', models.UUIDField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('user', 'User Report'), ('message', 'Message Report'), ('item', 'Marketplace Item Report')], max_length=10)),
                ('reason', models.TextField()),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='report_evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
